# This file has been disabled - using application.properties with MongoDB instead
# 
# Old PostgreSQL config (not needed):
# server:
#   error:
#     include-message: always
#     include-binding-errors: always
# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/registration
#     username: postgres
#     password: 5121
#     driver-class-name: org.postgresql.Driver
# jpa:
#   hibernate:
#   ddl-auto: create-drop
#   properties:
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      format_sql: true
#   show-sql: true
